### ISSUE TITLE
Conflicting property names

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/citemicroservices#3]
Our draft spec has "following" and "sequence" for property names on citable nodes, but the results are yielding "next" and "index"

**Comment by ThomasK81** [comment]
I commented the JSON up according our discussions here https://github.com/cite-architecture/cite-services-spec/blob/master/texts/1.0/notes/texts-GO_implementation.md and here https://github.com/cite-architecture/cite-services-spec/blob/c2c2c8e4d120feb8c0ca290056b7b712b27b3971/json-formatting.md . The latter disappeared when the repo was restructured. I don't feel strongly about the names though.

**Comment by neelsmith** [comment]
But that conflicts with the specification document https://github.com/cite-architecture/cite-services-spec/blob/master/texts/1.0/texts-specification-1.0.DRAFT.md

**Comment by ThomasK81** [comment]
Fixed as discussed: previous, next, and sequence are the new names.
