### ISSUE TITLE
Need version identifiers

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/citemicroservices#4]
strongly suggest using semantic versioning to identify releases of this software suite:  http://semver.org/

1. Other libraries in cite-architecture use semantic versioning, and consistency would be nice
2. Semantic version or equivalent essential in order to automate testing against specificaiton

**Comment by neelsmith** [comment]
One possibility:  since binaries for these services are not distributed through a dependency management system, perhaps just versioning appendix to the binary file name, eg, `citeMicros-1.0.0`

**Comment by ThomasK81** [comment]
Done.
