### ISSUE TITLE
Error in label of reply to cite request

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/citemicroservices#5]
Reply property is labelled `texts`:

```json
{
status: "Success",
texts: "1.0.0"
}
```

should be labelled `version`: 

```json
{
status: "Success",
version: "1.0.0"
}
```

**Comment by ThomasK81** [comment]
I think for this own we have to change the specs. The JSON will have more fields and we cannot call all of them version. Here is how the struct looks:
`type CITEResponse struct {
	Status         string `json:"status"`
	Texts          string `json:"texts,omitempty"`
	Textcatalog    string `json:"textcatalog,omitempty"`
	Citedata       string `json:"citedata,omitempty"`
	Citecatalog    string `json:"citecatalog,omitempty"`
	Citerelations  string `json:"citerelations,omitempty"`
	Citeextensions string `json:"citeextensions,omitempty"`
	DSE            string `json:"dse,omitempty"`
	ORCA           string `json:"orca,omitempty"`
}`

**Comment by ThomasK81** [comment]
This needs to be fixed: 
https://github.com/cite-architecture/cite-services-spec/blob/master/texts/1.0/texts-tests-1.0.DRAFT.json

It is not in accordance with our discussions. Not sure how to best embed them in here. 

<img width="1294" alt="screen shot 2017-06-06 at 23 17 15" src="https://user-images.githubusercontent.com/7259950/26852386-6b1f040c-4b0e-11e7-96cf-8928a07ed151.png">
