### ISSUE TITLE
Represent requestUrn as 0- or 1-element list?

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/citemicroservices#8]
`service` and `status` are *always* part of the metadata included in CITE microservices reply.  `requestUrn` is included for some requests, but not others.  

One clean way to represent that would be as a 0- or 1-element list.  Arguments in favor of this:  explicitly empty list is a clearer (because explicit) representation of this "optional" concept; it maps easily onto interpretations in client app languages.

It's a nice json idiom for the concept scala would use the `Option` class for, IMHO.

**Comment by ThomasK81** [comment]
Accepted and changed with https://github.com/cite-architecture/citemicroservices/commit/c68dec105d82be6b760729bc8a55dbe2ec7fdfd5
